export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const VIDEOS_FETCHED = "VIDEOS_FETCHED";
export const CATEGORIES_FETCHED = "CATEGORIES_FETCHED";
export const VIDEOS_FETCHED_BY_CATEGORY_ID = "VIDEOS_FETCHED_BY_CATEGORY_ID";
